image: node:18-alpine

stages:
  - build
  - build-docker
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash
    - apk add --no-cache git
    - apk add --no-cache openssh-client
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

build image:
  stage: build-docker
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build --platform linux/arm64 -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

deploy:
  stage: deploy
  script:
    - echo "deployment started!"
    - "which ssh-agent || ( apk update && apk add openssh-client )"
    - eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $USER@$IP_ADDRESS "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $USER@$IP_ADDRESS "docker pull $CI_REGISTRY_IMAGE"
    - ssh $USER@$IP_ADDRESS "docker stop mux-ui || true && docker rm mux-ui || true"
    - ssh $USER@$IP_ADDRESS "docker network create my-network || true"
    - ssh $USER@$IP_ADDRESS "docker run -d --name mux-ui --network my-network -p 5173:5173 -e VITE_API_URL=$VITE_API_URL $CI_REGISTRY_IMAGE"
  artifacts:
    paths:
      - dist/
